import { config, library } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
  faReact,
  faNodeJs,
  faJs,
  faHtml5,
  faCss3Alt,
  faVuejs,
  faDocker,
  faGitAlt,
  faGithub,
  faAws,
  faFigma,
  faNpm,
  faPython,
} from "@fortawesome/free-brands-svg-icons";
import {
  faCode,
  faServer,
  faDatabase,
  faWrench,
  faBolt,
  faLayerGroup,
  faGlobe,
  faRocket,
  faCube,
  faTerminal,
  faFire,
  faDiagramProject,
  faWandMagicSparkles,
  faMobileScreenButton,
  faGears,
  faVial,
  faTheaterMasks,
  faPaintBrush,
  faCircleNodes,
  faFileCode,
  faBrush,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
  faReact,
  faNodeJs,
  faJs,
  faHtml5,
  faCss3Alt,
  faVuejs,
  faDocker,
  faGitAlt,
  faGithub,
  faAws,
  faFigma,
  faNpm,
  faPython,
  faCode,
  faServer,
  faDatabase,
  faWrench,
  faBolt,
  faLayerGroup,
  faGlobe,
  faRocket,
  faCube,
  faTerminal,
  faFire,
  faDiagramProject,
  faWandMagicSparkles,
  faMobileScreenButton,
  faGears,
  faVial,
  faTheaterMasks,
  faPaintBrush,
  faCircleNodes,
  faFileCode,
  faBrush,
);
